### ISSUE TITLE
Crashes upon startup

### ISSUE THREAD

**Issue by beorn** [gliderlabs/logspout#162]
I'm trying to use logspout routing to papertrail, started from docker-compose, but it crashes upon startup.  The `docker-compose.yml` and log output is below.

```yml
  log:
    image: gliderlabs/logspout
    volumes:
     - "/var/run/docker.sock:/tmp/docker.sock"
    ports:
     - "18000:18000"
    environment:
     - PORT=18000
    command: syslog://logs3.papertrailapp.com:39833
```

```log
Attaching to hn_log_1, hn_hub_1
log_1 | 2016/02/27 01:43:08 routing all to syslog://logs3.papertrailapp.com:39833
log_1 | 2016/02/27 01:43:08 loading and persisting routes in /mnt/routes
log_1 | 2016/02/27 01:43:08 logspout v2 serving http on :18000
log_1 | 2016/02/27 01:45:55 syslog: dial udp: lookup logs3.papertrailapp.com: Try again
log_1 | 2016/02/27 01:48:06 routing all to syslog://logs3.papertrailapp.com:39833
log_1 | 2016/02/27 01:48:06 loading and persisting routes in /mnt/routes
log_1 | 2016/02/27 01:48:06 logspout v2 serving http on :18000
log_1 | panic: runtime error: slice bounds out of range
log_1 | 
log_1 | goroutine 23 [running]:
log_1 | runtime.panic(0x770ea0, 0x9b4a2f)
log_1 | 	/usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
log_1 | main.func·001()
log_1 | 	/go/src/github.com/progrium/logspout/attacher.go:35 +0x370
log_1 | created by main.NewAttachManager
log_1 | 	/go/src/github.com/progrium/logspout/attacher.go:41 +0x2c4
log_1 | 
log_1 | goroutine 16 [IO wait, 3 minutes]:
log_1 | net.runtime_pollWait(0x7ff02922b6d0, 0x72, 0x0)
log_1 | 	/usr/lib/go/src/pkg/runtime/netpoll.goc:146 +0x66
log_1 | net.(*pollDesc).Wait(0xc20802baa0, 0x72, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
log_1 | net.(*pollDesc).WaitRead(0xc20802baa0, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
log_1 | net.(*netFD).accept(0xc20802ba40, 0x873090, 0x0, 0x7ff02922a2e0, 0xb)
log_1 | 	/usr/lib/go/src/pkg/net/fd_unix.go:419 +0x343
log_1 | net.(*TCPListener).AcceptTCP(0xc20803a118, 0xc20806f950, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
log_1 | net/http.tcpKeepAliveListener.Accept(0xc20803a118, 0x0, 0x0, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/net/http/server.go:1947 +0x4b
log_1 | net/http.(*Server).Serve(0xc208004840, 0x7ff02922c0d0, 0xc20803a118, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/net/http/server.go:1698 +0x91
log_1 | net/http.(*Server).ListenAndServe(0xc208004840, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/net/http/server.go:1688 +0x14d
log_1 | net/http.ListenAndServe(0xc20807a7d0, 0x6, 0x7ff02922bfc8, 0xc20800e820, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/net/http/server.go:1778 +0x79
log_1 | main.main()
log_1 | 	/go/src/github.com/progrium/logspout/logspout.go:298 +0x13d3
log_1 | 
log_1 | goroutine 19 [finalizer wait, 3 minutes]:
log_1 | runtime.park(0x41ee00, 0x9b8a78, 0x9b6cc9)
log_1 | 	/usr/lib/go/src/pkg/runtime/proc.c:1369 +0x89
log_1 | runtime.parkunlock(0x9b8a78, 0x9b6cc9)
log_1 | 	/usr/lib/go/src/pkg/runtime/proc.c:1385 +0x3b
log_1 | runfinq()
log_1 | 	/usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xcf
log_1 | runtime.goexit()
log_1 | 	/usr/lib/go/src/pkg/runtime/proc.c:1445
log_1 | 
log_1 | goroutine 20 [chan receive, 3 minutes]:
log_1 | github.com/fsouza/go-dockerclient.(*Client).hijack(0xc208046600, 0x7bd9f0, 0x4, 0xc20804e040, 0x3a, 0xc208004480, 0xc20800e000, 0x0, 0x0, 0x7ff02922bc30, ...)
log_1 | 	/go/src/github.com/fsouza/go-dockerclient/client.go:512 +0x808
log_1 | github.com/fsouza/go-dockerclient.(*Client).AttachToContainer(0xc208046600, 0xc20804ea00, 0xc, 0x0, 0x0, 0x7ff02922bc30, 0xc20803a080, 0x7ff02922bc30, 0xc20803a098, 0x101000100, ...)
log_1 | 	/go/src/github.com/fsouza/go-dockerclient/container.go:702 +0x257
log_1 | main.func·002()
log_1 | 	/go/src/github.com/progrium/logspout/attacher.go:63 +0x165
log_1 | created by main.(*AttachManager).attach
log_1 | 	/go/src/github.com/progrium/logspout/attacher.go:75 +0x2b2
log_1 | 
log_1 | goroutine 21 [semacquire, 3 minutes]:
log_1 | sync.runtime_Syncsemacquire(0xc2080541c0)
log_1 | 	/usr/lib/go/src/pkg/runtime/sema.goc:257 +0xc0
log_1 | sync.(*Cond).Wait(0xc2080541b0)
log_1 | 	/usr/lib/go/src/pkg/sync/cond.go:62 +0x9d
log_1 | io.(*pipe).read(0xc208054180, 0xc208072000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/io/pipe.go:52 +0x2b6
log_1 | io.(*PipeReader).Read(0xc20803a078, 0xc208072000, 0x1000, 0x1000, 0x40fe58, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/io/pipe.go:134 +0x5f
log_1 | bufio.(*Reader).fill(0xc2080048a0)
log_1 | 	/usr/lib/go/src/pkg/bufio/bufio.go:97 +0x1b3
log_1 | bufio.(*Reader).ReadSlice(0xc2080048a0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/bufio/bufio.go:298 +0x22c
log_1 | bufio.(*Reader).ReadBytes(0xc2080048a0, 0xc20803a00a, 0x0, 0x0, 0x0, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/bufio/bufio.go:376 +0xe3
log_1 | main.func·005(0x7c71d0, 0x6, 0x7ff02922bc80, 0xc20803a078)
log_1 | 	/go/src/github.com/progrium/logspout/attacher.go:169 +0x7a
log_1 | created by main.NewLogPump
log_1 | 	/go/src/github.com/progrium/logspout/attacher.go:184 +0x15e
log_1 | 
log_1 | goroutine 22 [semacquire, 3 minutes]:
log_1 | sync.runtime_Syncsemacquire(0xc208054280)
log_1 | 	/usr/lib/go/src/pkg/runtime/sema.goc:257 +0xc0
log_1 | sync.(*Cond).Wait(0xc208054270)
log_1 | 	/usr/lib/go/src/pkg/sync/cond.go:62 +0x9d
log_1 | io.(*pipe).read(0xc208054240, 0xc208073000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/io/pipe.go:52 +0x2b6
log_1 | io.(*PipeReader).Read(0xc20803a090, 0xc208073000, 0x1000, 0x1000, 0xc2, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/io/pipe.go:134 +0x5f
log_1 | bufio.(*Reader).fill(0xc208004900)
log_1 | 	/usr/lib/go/src/pkg/bufio/bufio.go:97 +0x1b3
log_1 | bufio.(*Reader).ReadSlice(0xc208004900, 0x41ee0a, 0x0, 0x0, 0x0, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/bufio/bufio.go:298 +0x22c
log_1 | bufio.(*Reader).ReadBytes(0xc208004900, 0xc20804ed0a, 0x0, 0x0, 0x0, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/bufio/bufio.go:376 +0xe3
log_1 | main.func·005(0x7c7190, 0x6, 0x7ff02922bc80, 0xc20803a090)
log_1 | 	/go/src/github.com/progrium/logspout/attacher.go:169 +0x7a
log_1 | created by main.NewLogPump
log_1 | 	/go/src/github.com/progrium/logspout/attacher.go:185 +0x197
log_1 | 
log_1 | goroutine 24 [select, 3 minutes]:
log_1 | main.(*AttachManager).Listen(0xc20800e7a0, 0x7ff028ed0eb0, 0xc208004a20, 0xc208004420)
log_1 | 	/go/src/github.com/progrium/logspout/attacher.go:129 +0x6fc
log_1 | main.func·012()
log_1 | 	/go/src/github.com/progrium/logspout/routes.go:91 +0x17c
log_1 | created by main.(*RouteManager).Add
log_1 | 	/go/src/github.com/progrium/logspout/routes.go:92 +0x555
log_1 | 
log_1 | goroutine 25 [IO wait, 3 minutes]:
log_1 | net.runtime_pollWait(0x7ff02922b780, 0x72, 0x0)
log_1 | 	/usr/lib/go/src/pkg/runtime/netpoll.goc:146 +0x66
log_1 | net.(*pollDesc).Wait(0xc20802a290, 0x72, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
log_1 | net.(*pollDesc).WaitRead(0xc20802a290, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
log_1 | net.(*netFD).Read(0xc20802a230, 0xc208088000, 0x8009, 0x8009, 0x0, 0x7ff02922a2e0, 0xb)
log_1 | 	/usr/lib/go/src/pkg/net/fd_unix.go:242 +0x34c
log_1 | net.(*conn).Read(0xc20803a018, 0xc208088000, 0x8009, 0x8009, 0x0, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/net/net.go:122 +0xe7
log_1 | bufio.(*Reader).Read(0xc2080042a0, 0xc208088000, 0x8009, 0x8009, 0x8009, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/bufio/bufio.go:165 +0x13b
log_1 | github.com/fsouza/go-dockerclient.stdCopy(0x7ff02922bc30, 0xc20803a080, 0x7ff02922bc30, 0xc20803a098, 0x7ff02922b958, 0xc2080042a0, 0xc2, 0x0, 0x0)
log_1 | 	/go/src/github.com/fsouza/go-dockerclient/stdcopy.go:33 +0x16b
log_1 | github.com/fsouza/go-dockerclient.func·001()
log_1 | 	/go/src/github.com/fsouza/go-dockerclient/client.go:498 +0x1d2
log_1 | created by github.com/fsouza/go-dockerclient.(*Client).hijack
log_1 | 	/go/src/github.com/fsouza/go-dockerclient/client.go:501 +0x79b
log_1 | 
log_1 | goroutine 27 [select]:
log_1 | github.com/fsouza/go-dockerclient.(*eventMonitoringState).monitorEvents(0xc20802a700, 0xc208046600)
log_1 | 	/go/src/github.com/fsouza/go-dockerclient/event.go:175 +0x376
log_1 | created by github.com/fsouza/go-dockerclient.(*eventMonitoringState).enableEventMonitoring
log_1 | 	/go/src/github.com/fsouza/go-dockerclient/event.go:148 +0x113
log_1 | 
log_1 | goroutine 28 [chan receive, 3 minutes]:
log_1 | main.syslogStreamer(0x7ffcc1d47f3f, 0x6, 0x7ffcc1d47f48, 0x1d, 0x0, 0x0, 0x0, 0x0, 0x9b9508, 0x0, ...)
log_1 | 	/go/src/github.com/progrium/logspout/logspout.go:63 +0x10c
log_1 | created by main.func·012
log_1 | 	/go/src/github.com/progrium/logspout/routes.go:87 +0x228
log_1 | 
log_1 | goroutine 30 [IO wait]:
log_1 | net.runtime_pollWait(0x7ff02922b620, 0x72, 0x0)
log_1 | 	/usr/lib/go/src/pkg/runtime/netpoll.goc:146 +0x66
log_1 | net.(*pollDesc).Wait(0xc20802bb80, 0x72, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
log_1 | net.(*pollDesc).WaitRead(0xc20802bb80, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
log_1 | net.(*netFD).Read(0xc20802bb20, 0xc208074000, 0x1000, 0x1000, 0x0, 0x7ff02922a2e0, 0xb)
log_1 | 	/usr/lib/go/src/pkg/net/fd_unix.go:242 +0x34c
log_1 | net.(*conn).Read(0xc20803a180, 0xc208074000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/net/net.go:122 +0xe7
log_1 | bufio.(*Reader).fill(0xc208004ae0)
log_1 | 	/usr/lib/go/src/pkg/bufio/bufio.go:97 +0x1b3
log_1 | bufio.(*Reader).ReadSlice(0xc208004ae0, 0x9d390a, 0x0, 0x0, 0x0, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/bufio/bufio.go:298 +0x22c
log_1 | net/http.readLine(0xc208004ae0, 0x0, 0x0, 0x0, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/net/http/chunked.go:111 +0x59
log_1 | net/http.(*chunkedReader).beginChunk(0xc2080236e0)
log_1 | 	/usr/lib/go/src/pkg/net/http/chunked.go:48 +0x45
log_1 | net/http.(*chunkedReader).Read(0xc2080236e0, 0xc2080b2001, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/net/http/chunked.go:78 +0xc0
log_1 | net/http.(*body).readLocked(0xc20804e980, 0xc2080b2001, 0x5ff, 0x5ff, 0x6b0c60, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/net/http/transfer.go:577 +0x81
log_1 | net/http.(*body).Read(0xc20804e980, 0xc2080b2001, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/net/http/transfer.go:572 +0x11a
log_1 | encoding/json.(*Decoder).readValue(0xc20802c340, 0x4e, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/encoding/json/stream.go:124 +0x557
log_1 | encoding/json.(*Decoder).Decode(0xc20802c340, 0x6a3040, 0xc2080af380, 0x0, 0x0)
log_1 | 	/usr/lib/go/src/pkg/encoding/json/stream.go:44 +0x7a
log_1 | github.com/fsouza/go-dockerclient.func·004(0xc2080442d0, 0xc20803c370)
log_1 | 	/go/src/github.com/fsouza/go-dockerclient/event.go:289 +0x18b
log_1 | created by github.com/fsouza/go-dockerclient.(*Client).eventHijack
log_1 | 	/go/src/github.com/fsouza/go-dockerclient/event.go:307 +0x4a6
log_1 | 
log_1 | goroutine 17 [syscall, 3 minutes]:
log_1 | runtime.goexit()
log_1 | 	/usr/lib/go/src/pkg/runtime/proc.c:1445
```

**Comment by janeczku** [comment]
This is fixed in master, see https://github.com/gliderlabs/logspout/issues/37

`image: gliderlabs/logspout:master`

**Comment by michaelshobbs** [comment]
Can we get this fix released to latest? @progrium

**Comment by mattaitchison** [comment]
#166
