### ISSUE TITLE
Logspout crash

### ISSUE THREAD

**Issue by mhariri** [gliderlabs/logspout#183]
Logspout crashed, with this stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x48f476]

goroutine 1257 [running]:
panic(0x86e880, 0xc82000a090)
        /usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/gliderlabs/logspout/router.(*LogsPump).rename(0xc8200e12e0, 0xc8200a0380)
        /go/src/github.com/gliderlabs/logspout/router/pump.go:98 +0x186
created by github.com/gliderlabs/logspout/router.(*LogsPump).Run
        /go/src/github.com/gliderlabs/logspout/router/pump.go:123 +0x7b4
```

I'm running gliderlabs/logspout:master using syslog+tcp adapter, if that matters.

**Comment by michaelshobbs** [comment]
Can you provide the docker command you used to start the container?

**Comment by mhariri** [comment]
I'm using docker-compose, and this is the section for logspout:

```
logspout:
  image: gliderlabs/logspout
  environment:
    DEBUG: "true"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  links:
     - logstash
  command: syslog://logstash:5000
```

**Comment by patrick-armitage** [comment]
I get repeated crashes as well

```
 Main PID: 17203 (code=exited, status=2)

May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: github.com/fsouza/go-dockerclient.stdCopy(0x7f67ffe9bc08, 0xc20803a4d0, 0x7f67ffe9bc08, 0xc20803a4e8, 0x7f67ffe9b958, 0xc20811...0, 0x0, 0x0)
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: /go/src/github.com/fsouza/go-dockerclient/stdcopy.go:33 +0x16b
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: github.com/fsouza/go-dockerclient.func·001()
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: /go/src/github.com/fsouza/go-dockerclient/client.go:498 +0x1d2
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: created by github.com/fsouza/go-dockerclient.(*Client).hijack
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: /go/src/github.com/fsouza/go-dockerclient/client.go:501 +0x79b
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: goroutine 80 [chan receive]:
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: github.com/fsouza/go-dockerclient.(*Client).hijack(0xc208046600, 0x7bd9f0, 0x4, 0xc208150440, 0x3a, 0xc208115080, 0xc208116a00...e9bc08, ...)
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: /go/src/github.com/fsouza/go-dockerclient/client.go:512 +0x808
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: github.com/fsouza/go-dockerclient.(*Client).AttachToContainer(0xc208046600, 0xc20804f1c0, 0xc, 0x0, 0x0, 0x7f67ffe9bc08, 0xc20...000100, ...)
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: /go/src/github.com/fsouza/go-dockerclient/container.go:702 +0x257
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: main.func·002()
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: /go/src/github.com/progrium/logspout/attacher.go:63 +0x165
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: created by main.(*AttachManager).attach
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: /go/src/github.com/progrium/logspout/attacher.go:75 +0x2b2
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: goroutine 81 [semacquire]:
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: sync.runtime_Syncsemacquire(0xc208055c00)
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: /usr/lib/go/src/pkg/runtime/sema.goc:257 +0xc0
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: sync.(*Cond).Wait(0xc208055bf0)
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: /usr/lib/go/src/pkg/sync/cond.go:62 +0x9d
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: io.(*pipe).read(0xc208055bc0, 0xc20816d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: /usr/lib/go/src/pkg/io/pipe.go:52 +0x2b6
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: io.(*PipeReader).Read(0xc20803a540, 0xc20816d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: /usr/lib/go/src/pkg/io/pipe.go:134 +0x5f
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: bufio.(*Reader).fill(0xc2081155c0)
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: /usr/lib/go/src/pkg/bufio/bufio.go:97 +0x1b3
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: bufio.(*Reader).ReadSlice(0xc2081155c0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: /usr/lib/go/src/pkg/bufio/bufio.go:298 +0x22c
May 17 18:57:39 ip-10-100-2-77.ec2.internal sh[17203]: bufio.(*Reader).ReadBytes(0xc2081155c0, 0xc20803a50a, 0x0, 0x0, 0x0, 0x0, 0x0)
```

**Comment by mattaitchison** [comment]
Reopen if 1bfbc27 doesn't resolve this.
