### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jbergknoff** [gliderlabs/logspout#2]
I've just had this happen:

``` bash
$ sudo docker.io -v
Docker version 0.9.1, build 3600720
$ sudo docker.io run -d -e "DEBUG=true" -p 8000:8000 -v=/var/run/docker.sock:/tmp/docker.sock progrium/logspout syslog://logs.papertrailapp.com:55555
219c6567d3e07d55d73f0be91f4df34b36ab0464777da7d7dbf6964456015ec3
$ sudo docker.io run stackbrew/ubuntu:13.10 echo hello world
hello world
$ sudo docker.io ps -a
CONTAINER ID        IMAGE                      COMMAND                CREATED              STATUS              PORTS               NAMES
49c83861e5bb        stackbrew/ubuntu:13.10     echo hello world       50 seconds ago       Exit 0                                  condescending_mclean   
219c6567d3e0        progrium/logspout:latest   /bin/logspout syslog   About a minute ago   Exit 2                                  happy_bardeen          
$ sudo docker.io logs 219
2014/05/25 03:14:47 attach: 219c6567d3e0 success
2014/05/25 03:14:47 routing all to syslog://logs.papertrailapp.com:55555
2014/05/25 03:14:47 loading and persisting routes in /mnt/routes
2014/05/25 03:14:47 logspout serving http on :8000
[martini] Started GET /logs for 172.17.42.1:59760
2014/05/25 03:15:05 event: 49c83861e5bb create
2014/05/25 03:15:05 event: 49c83861e5bb start
2014/05/25 03:15:05 attach: 49c83861e5bb success
2014/05/25 03:15:05 attach: 49c83861e5bb finished
2014/05/25 03:15:05 event: 49c83861e5bb die
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x45e7cd]

goroutine 11 [running]:
runtime.panic(0x69ac20, 0xa01e48)
    /usr/local/go/src/pkg/runtime/panic.c:266 +0xb6
log/syslog.(*Writer).Write(0x0, 0xc2100cdf80, 0x31, 0x31, 0x31, ...)
    /usr/local/go/src/pkg/log/syslog/syslog.go:178 +0x5d
io.WriteString(0x7f0056810260, 0x0, 0xc2100b8080, 0x31, 0xe, ...)
    /usr/local/go/src/pkg/io/io.go:272 +0xdf
main.syslogStreamer(0x7fff0b321f24, 0x6, 0x7fff0b321f2d, 0x1c, 0x0, ...)
    /vagrant/logspout/logspout.go:65 +0x224
created by main.func·012
    /vagrant/logspout/routes.go:83 +0xbc

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7f005680f290, 0x72, 0x0)
    /usr/local/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc21007ab50, 0x72, 0x7f005680e0c0, 0xb)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc21007ab50, 0xb, 0x7f005680e0c0)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).accept(0xc21007aaf0, 0x786310, 0x0, 0x7f005680e0c0, 0xb)
    /usr/local/go/src/pkg/net/fd_unix.go:382 +0x2c2
net.(*TCPListener).AcceptTCP(0xc210000d88, 0x4755fb, 0x7f005666ed08, 0x4755fb)
    /usr/local/go/src/pkg/net/tcpsock_posix.go:233 +0x47
net.(*TCPListener).Accept(0xc210000d88, 0x7f005680fcd8, 0xc210000e50, 0xc210060b80, 0x0)
    /usr/local/go/src/pkg/net/tcpsock_posix.go:243 +0x27
net/http.(*Server).Serve(0xc210078640, 0x7f005680fc00, 0xc210000d88, 0x0, 0x0)
    /usr/local/go/src/pkg/net/http/server.go:1622 +0x91
net/http.(*Server).ListenAndServe(0xc210078640, 0xc210078640, 0x7f005666ee08)
    /usr/local/go/src/pkg/net/http/server.go:1612 +0xa0
net/http.ListenAndServe(0xc210000d60, 0x5, 0x7f005680fb80, 0xc21000a140, 0x4, ...)
    /usr/local/go/src/pkg/net/http/server.go:1677 +0x6d
main.main()
    /vagrant/logspout/logspout.go:220 +0xc58

goroutine 3 [chan receive]:
github.com/fsouza/go-dockerclient.(*Client).hijack(0xc21000a4c0, 0x6f3740, 0x4, 0xc210058480, 0x3a, ...)
    /home/vagrant/.go/src/github.com/fsouza/go-dockerclient/client.go:227 +0x48a
github.com/fsouza/go-dockerclient.(*Client).AttachToContainer(0xc21000a4c0, 0xc21001f460, 0xc, 0x0, 0x0, ...)
    /home/vagrant/.go/src/github.com/fsouza/go-dockerclient/container.go:538 +0x1e6
main.func·002()
    /vagrant/logspout/attacher.go:63 +0x133
created by main.(*AttachManager).attach
    /vagrant/logspout/attacher.go:75 +0x271

goroutine 4 [semacquire]:
sync.runtime_Syncsemacquire(0xc21006b1c0)
    /usr/local/go/src/pkg/runtime/sema.goc:257 +0xca
sync.(*Cond).Wait(0xc21006b1b0)
    /usr/local/go/src/pkg/sync/cond.go:62 +0x89
io.(*pipe).read(0xc21006b180, 0xc21007d000, 0x1000, 0x1000, 0x0, ...)
    /usr/local/go/src/pkg/io/pipe.go:52 +0x245
io.(*PipeReader).Read(0xc210000940, 0xc21007d000, 0x1000, 0x1000, 0x426a19, ...)
    /usr/local/go/src/pkg/io/pipe.go:134 +0x5f
bufio.(*Reader).fill(0xc21000bc00)
    /usr/local/go/src/pkg/bufio/bufio.go:91 +0x110
bufio.(*Reader).ReadSlice(0xc21000bc00, 0x40c70a, 0x0, 0x0, 0x0, ...)
    /usr/local/go/src/pkg/bufio/bufio.go:274 +0x204
bufio.(*Reader).ReadBytes(0xc21000bc00, 0xc21009250a, 0x0, 0x0, 0x0, ...)
    /usr/local/go/src/pkg/bufio/bufio.go:355 +0xbf
main.func·005(0x6fbfe0, 0x6, 0x7f005680f808, 0xc210000940)
    /vagrant/logspout/attacher.go:168 +0x77
created by main.NewLogPump
    /vagrant/logspout/attacher.go:183 +0x164

goroutine 5 [chan send]:
main.(*LogPump).send(0xc21006f990, 0xc2100b8200)
    /vagrant/logspout/attacher.go:193 +0xbd
main.func·005(0x6fbfc0, 0x6, 0x7f005680f808, 0xc210000958)
    /vagrant/logspout/attacher.go:180 +0x354
created by main.NewLogPump
    /vagrant/logspout/attacher.go:184 +0x19d

goroutine 6 [chan receive]:
main.func·001()
    /vagrant/logspout/attacher.go:34 +0xb9
created by main.NewAttachManager
    /vagrant/logspout/attacher.go:41 +0x2ab

goroutine 7 [select]:
main.(*AttachManager).Listen(0xc21000a4e0, 0x7f0056682ed8, 0xc21000bd20, 0xc21000b600)
    /vagrant/logspout/attacher.go:129 +0x50c
main.func·012()
    /vagrant/logspout/routes.go:84 +0xfa
created by main.(*RouteManager).Add
    /vagrant/logspout/routes.go:85 +0x521

goroutine 8 [runnable]:
net.runtime_pollWait(0x7f005680f338, 0x72, 0x0)
    /usr/local/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc21004fae0, 0x72, 0x7f005680e0c0, 0xb)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc21004fae0, 0xb, 0x7f005680e0c0)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).Read(0xc21004fa80, 0xc210081000, 0x8009, 0x8009, 0x0, ...)
    /usr/local/go/src/pkg/net/fd_unix.go:204 +0x2a0
net.(*conn).Read(0xc210000a50, 0xc210081000, 0x8009, 0x8009, 0xc210081008, ...)
    /usr/local/go/src/pkg/net/net.go:122 +0xc5
bufio.(*Reader).Read(0xc21000b5a0, 0xc210081000, 0x8009, 0x8009, 0x8009, ...)
    /usr/local/go/src/pkg/bufio/bufio.go:152 +0x106
github.com/fsouza/go-dockerclient/utils.StdCopy(0x7f005680f7b8, 0xc210000948, 0x7f005680f7b8, 0xc210000960, 0x7f005680f530, ...)
    /home/vagrant/.go/src/github.com/fsouza/go-dockerclient/utils/stdcopy.go:88 +0x129
github.com/fsouza/go-dockerclient.func·001()
    /home/vagrant/.go/src/github.com/fsouza/go-dockerclient/client.go:213 +0x123
created by github.com/fsouza/go-dockerclient.(*Client).hijack
    /home/vagrant/.go/src/github.com/fsouza/go-dockerclient/client.go:216 +0x42c

goroutine 10 [select]:
github.com/fsouza/go-dockerclient.(*eventMonitoringState).monitorEvents(0xa070c0, 0xc21000a4c0)
    /home/vagrant/.go/src/github.com/fsouza/go-dockerclient/event.go:163 +0x2ff
created by github.com/fsouza/go-dockerclient.(*eventMonitoringState).enableEventMonitoring
    /home/vagrant/.go/src/github.com/fsouza/go-dockerclient/event.go:136 +0x111

goroutine 13 [IO wait]:
net.runtime_pollWait(0x7f005680f1e8, 0x72, 0x0)
    /usr/local/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc21007ae60, 0x72, 0x7f005680e0c0, 0xb)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc21007ae60, 0xb, 0x7f005680e0c0)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).Read(0xc21007ae00, 0xc21008f000, 0x1000, 0x1000, 0x0, ...)
    /usr/local/go/src/pkg/net/fd_unix.go:204 +0x2a0
net.(*conn).Read(0xc210000e10, 0xc21008f000, 0x1000, 0x1000, 0x0, ...)
    /usr/local/go/src/pkg/net/net.go:122 +0xc5
bufio.(*Reader).fill(0xc21000bea0)
    /usr/local/go/src/pkg/bufio/bufio.go:91 +0x110
bufio.(*Reader).Read(0xc21000bea0, 0xc2100911b5, 0xe4b, 0xe4b, 0xe4b, ...)
    /usr/local/go/src/pkg/bufio/bufio.go:159 +0x1a4
bufio.(*Scanner).Scan(0xc21008d150, 0xc210074c00)
    /usr/local/go/src/pkg/bufio/scan.go:165 +0x487
github.com/fsouza/go-dockerclient.func·004(0x7f005680f530, 0xc21000bea0)
    /home/vagrant/.go/src/github.com/fsouza/go-dockerclient/event.go:264 +0x152
created by github.com/fsouza/go-dockerclient.(*Client).eventHijack
    /home/vagrant/.go/src/github.com/fsouza/go-dockerclient/event.go:280 +0x4a1

goroutine 15 [select]:
main.(*AttachManager).Listen(0xc21000a4e0, 0x7f005664cb08, 0xc21000b0c0, 0xc21000b120)
    /vagrant/logspout/attacher.go:129 +0x50c
main.func·007(0x7f005680fef8, 0xc210092400, 0xc21006c5b0, 0xc210099090)
    /vagrant/logspout/logspout.go:181 +0x326
reflect.Value.call(0x666380, 0xc21001ee50, 0x130, 0x6f05e0, 0x4, ...)
    /usr/local/go/src/pkg/reflect/value.go:474 +0xe0b
reflect.Value.Call(0x666380, 0xc21001ee50, 0x130, 0xc210078960, 0x3, ...)
    /usr/local/go/src/pkg/reflect/value.go:345 +0x9d
github.com/codegangsta/inject.(*injector).Invoke(0xc21007c3c0, 0x666380, 0xc21001ee50, 0x56f9ae, 0x620fe0, ...)
    /home/vagrant/.go/src/github.com/codegangsta/inject/inject.go:102 +0x304
github.com/go-martini/martini.(*context).Invoke(0xc2100787d0, 0x666380, 0xc21001ee50, 0x6ac100, 0x4ad6a0, ...)
    /home/vagrant/.go/src/github.com/go-martini/martini/env.go:1 +0x4c
github.com/go-martini/martini.(*routeContext).run(0xc2100990c0)
    /home/vagrant/.go/src/github.com/go-martini/martini/router.go:350 +0x74
github.com/go-martini/martini.(*route).Handle(0xc21001feb0, 0x7f005680ff30, 0xc2100787d0, 0x7f005680fef8, 0xc210092400)
    /home/vagrant/.go/src/github.com/go-martini/martini/router.go:229 +0xe2
github.com/go-martini/martini.(*router).Handle(0xc21001fe10, 0x7f005680fef8, 0xc210092400, 0xc21006c5b0, 0x7f005680ff30, ...)
    /home/vagrant/.go/src/github.com/go-martini/martini/router.go:112 +0x16c
github.com/go-martini/martini.Router.Handle·fm(0x7f005680fef8, 0xc210092400, 0xc21006c5b0, 0x7f005680ff30, 0xc2100787d0)
    /home/vagrant/.go/src/github.com/go-martini/martini/martini.go:111 +0x60
reflect.Value.call(0x6662e0, 0xc21000a120, 0x130, 0x6f05e0, 0x4, ...)
    /usr/local/go/src/pkg/reflect/value.go:474 +0xe0b
reflect.Value.Call(0x6662e0, 0xc21000a120, 0x130, 0xc210078870, 0x3, ...)
    /usr/local/go/src/pkg/reflect/value.go:345 +0x9d
github.com/codegangsta/inject.(*injector).Invoke(0xc21007c3c0, 0x6662e0, 0xc21000a120, 0xa0fcd8, 0x0, ...)
    /home/vagrant/.go/src/github.com/codegangsta/inject/inject.go:102 +0x304
github.com/go-martini/martini.(*context).run(0xc2100787d0)
    /home/vagrant/.go/src/github.com/go-martini/martini/martini.go:165 +0x62
github.com/go-martini/martini.(*context).Next(0xc2100787d0)
    /home/vagrant/.go/src/github.com/go-martini/martini/martini.go:156 +0x2b
github.com/go-martini/martini.func·004(0x7f005680ff30, 0xc2100787d0, 0xc21001fe60)
    /home/vagrant/.go/src/github.com/go-martini/martini/recovery.go:140 +0x76
reflect.Value.call(0x644ba0, 0x783340, 0x130, 0x6f05e0, 0x4, ...)
    /usr/local/go/src/pkg/reflect/value.go:474 +0xe0b
reflect.Value.Call(0x644ba0, 0x783340, 0x130, 0xc210038ea0, 0x2, ...)
    /usr/local/go/src/pkg/reflect/value.go:345 +0x9d
github.com/codegangsta/inject.(*injector).Invoke(0xc21007c3c0, 0x644ba0, 0x783340, 0xc21001fe60, 0x7f005680fef8, ...)
    /home/vagrant/.go/src/github.com/codegangsta/inject/inject.go:102 +0x304
github.com/go-martini/martini.(*context).run(0xc2100787d0)
    /home/vagrant/.go/src/github.com/go-martini/martini/martini.go:165 +0x62
github.com/go-martini/martini.(*context).Next(0xc2100787d0)
    /home/vagrant/.go/src/github.com/go-martini/martini/martini.go:156 +0x2b
github.com/go-martini/martini.func·001(0x7f005680fef8, 0xc210092400, 0xc21006c5b0, 0x7f005680ff30, 0xc2100787d0, ...)
    /home/vagrant/.go/src/github.com/go-martini/martini/logger.go:25 +0x292
reflect.Value.call(0x67f6a0, 0x783330, 0x130, 0x6f05e0, 0x4, ...)
    /usr/local/go/src/pkg/reflect/value.go:474 +0xe0b
reflect.Value.Call(0x67f6a0, 0x783330, 0x130, 0xc21000bf60, 0x4, ...)
    /usr/local/go/src/pkg/reflect/value.go:345 +0x9d
github.com/codegangsta/inject.(*injector).Invoke(0xc21007c3c0, 0x67f6a0, 0x783330, 0xc21007c3c0, 0x7f005680fe40, ...)
    /home/vagrant/.go/src/github.com/codegangsta/inject/inject.go:102 +0x304
github.com/go-martini/martini.(*context).run(0xc2100787d0)
    /home/vagrant/.go/src/github.com/go-martini/martini/martini.go:165 +0x62
github.com/go-martini/martini.(*Martini).ServeHTTP(0xc210058680, 0x7f005680fe08, 0xc210079b40, 0xc21006c5b0)
    /home/vagrant/.go/src/github.com/go-martini/martini/martini.go:69 +0x53
net/http.serverHandler.ServeHTTP(0xc210078640, 0x7f005680fe08, 0xc210079b40, 0xc21006c5b0)
    /usr/local/go/src/pkg/net/http/server.go:1597 +0x16e
net/http.(*conn).serve(0xc210060b80)
    /usr/local/go/src/pkg/net/http/server.go:1167 +0x7b7
created by net/http.(*Server).Serve
    /usr/local/go/src/pkg/net/http/server.go:1644 +0x28b

goroutine 16 [chan receive]:
main.httpStreamer(0x7f005680fef8, 0xc210092400, 0xc21006c5b0, 0xc21000b0c0, 0x1)
    /vagrant/logspout/logspout.go:98 +0x1ac
created by main.func·007
    /vagrant/logspout/logspout.go:177 +0x397

goroutine 17 [IO wait]:
net.runtime_pollWait(0x7f005680f140, 0x72, 0x0)
    /usr/local/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc21008dfb0, 0x72, 0x7f005680e0c0, 0xb)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc21008dfb0, 0xb, 0x7f005680e0c0)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).Read(0xc21008df50, 0xc21009a000, 0x8000, 0x8000, 0x0, ...)
    /usr/local/go/src/pkg/net/fd_unix.go:204 +0x2a0
net.(*conn).Read(0xc210000e50, 0xc21009a000, 0x8000, 0x8000, 0x8000, ...)
    /usr/local/go/src/pkg/net/net.go:122 +0xc5
io.Copy(0x7f005680f7b8, 0xc210000ed8, 0x7f005680fd38, 0xc210000e50, 0x0, ...)
    /usr/local/go/src/pkg/io/io.go:352 +0x1c8
net/http.func·006()
    /usr/local/go/src/pkg/net/http/server.go:161 +0x68
created by net/http.(*conn).closeNotify
    /usr/local/go/src/pkg/net/http/server.go:167 +0x1f5

goroutine 19 [syscall]:
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1394
```

I also curled for the logs, and the output there was:

``` bash
$ curl $(sudo docker.io port `sudo docker.io ps -lq` 8000)/logs
   happy_bardeen|[martini] Started GET /logs for 172.17.42.1:59760
   happy_bardeen|2014/05/25 03:15:05 event: 49c83861e5bb create
   happy_bardeen|2014/05/25 03:15:05 event: 49c83861e5bb start
   happy_bardeen|2014/05/25 03:15:05 attach: 49c83861e5bb success
condescending_mclean|hello world
curl: (18) transfer closed with outstanding read data remaining
```

**Comment by jmstone617** [comment]
Is this actually fixed? I'm still seeing this same error a year later on Docker 1.6. Logspout will run for a while, and then randomly die. Logs show the following:

    2015/06/02 23:18:32 routing all to syslog://logs.papertrailapp.com:[redacted]
    2015/06/02 23:18:32 loading and persisting routes in /mnt/routes
    2015/06/02 23:18:32 logspout v2 serving http on :8000
    2015/06/03 10:51:18 syslog: dial udp: lookup logs.papertrailapp.com: Try again

Output of `docker version`:

    Client version: 1.6.0
    Client API version: 1.18
    Go version (client): go1.4.2
    Git commit (client): 4749651
    OS/Arch (client): linux/amd64
    Server version: 1.6.0
    Server API version: 1.18
    Go version (server): go1.4.2
    Git commit (server): 4749651
    OS/Arch (server): linux/amd64

Logspout is from the `latest` tag, created about 11 weeks ago. Anyone else seeing this?

**Comment by progrium** [comment]
Try :master

**Comment by jmstone617** [comment]
Running `master` tag now with `-e DEBUG=true`. Will update here if/when I have more information. Thanks!

**Comment by jmstone617** [comment]
It's still running but I'm not actually seeing any of my log data get routed.

I'm starting logspout with the following command:
`docker run -d --name logspout --volume=/var/run/docker.sock:/tmp/docker.sock -h beta gliderlabs/logspout:master syslog://logs.papertrailapp.com:[IP ADDRESS]`
