### ISSUE TITLE
panic: runtime error: assignment to entry in nil map

### ISSUE THREAD

**Issue by nagliyvred** [gliderlabs/logspout#75]
Hi @progrium,

When I run the current master pointing to loggly url like that: `rfc5424://logs-01.loggly.com:514?structuredData=<token>@41058`
I get an exception like that: 
```
2015-04-07T00:48:16.268748415Z # logspout v3-master by gliderlabs
2015-04-07T00:48:16.268825080Z # adapters: tcp syslog raw udp
2015-04-07T00:48:16.268952603Z # options : persist:/mnt/routes
2015-04-07T00:48:16.269574474Z panic: runtime error: assignment to entry in nil map
2015-04-07T00:48:16.269611719Z 
2015-04-07T00:48:16.269611719Z goroutine 16 [running]:
2015-04-07T00:48:16.269611719Z runtime.panic(0x7af000, 0xa1d5d3)
2015-04-07T00:48:16.269611719Z 	/usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
2015-04-07T00:48:16.269611719Z github.com/gliderlabs/logspout/router.(*RouteManager).AddFromUri(0xc208024de0, 0x7fff0d7f8d38, 0x5a, 0x0, 0x0)
2015-04-07T00:48:16.269611719Z 	/go/src/github.com/gliderlabs/logspout/router/routes.go:102 +0x4b3
2015-04-07T00:48:16.269611719Z github.com/gliderlabs/logspout/router.(*RouteManager).Setup(0xc208024de0, 0x0, 0x0)
2015-04-07T00:48:16.269611719Z 	/go/src/github.com/gliderlabs/logspout/router/routes.go:184 +0x1bb
2015-04-07T00:48:16.269611719Z main.main()
2015-04-07T00:48:16.269611719Z 	/go/src/github.com/gliderlabs/logspout/logspout.go:39 +0x646
2015-04-07T00:48:16.269611719Z 
2015-04-07T00:48:16.269611719Z goroutine 17 [runnable]:
2015-04-07T00:48:16.269611719Z runtime.MHeap_Scavenger()
2015-04-07T00:48:16.269611719Z 	/usr/lib/go/src/pkg/runtime/mheap.c:507
2015-04-07T00:48:16.269611719Z runtime.goexit()
2015-04-07T00:48:16.269611719Z 	/usr/lib/go/src/pkg/runtime/proc.c:1445
2015-04-07T00:48:16.269611719Z 
2015-04-07T00:48:16.269611719Z goroutine 18 [runnable]:
2015-04-07T00:48:16.269611719Z bgsweep()
2015-04-07T00:48:16.269611719Z 	/usr/lib/go/src/pkg/runtime/mgc0.c:1976
2015-04-07T00:48:16.269611719Z runtime.goexit()
2015-04-07T00:48:16.269611719Z 	/usr/lib/go/src/pkg/runtime/proc.c:1445
2015-04-07T00:48:16.269611719Z 
2015-04-07T00:48:16.269611719Z goroutine 19 [runnable]:
2015-04-07T00:48:16.269611719Z runfinq()
2015-04-07T00:48:16.269611719Z 	/usr/lib/go/src/pkg/runtime/mgc0.c:2606
2015-04-07T00:48:16.269611719Z runtime.goexit()
2015-04-07T00:48:16.269611719Z 	/usr/lib/go/src/pkg/runtime/proc.c:1445
```

The same url seems to be working in `latest` image, but in `latest` once a slightly longer log entry occures, it blows up with `write udp 54.236.80.3:514: message too long`

Is there an issue or am I doing something wrong?

Thanks,
Evgeny

**Comment by progrium** [comment]
Docs are not catching up to changes in master. For starters, rfc5424 was replaced as just the default syslog adapter. Best docs for that adapter is the source right now: https://github.com/gliderlabs/logspout/blob/master/adapters/syslog/syslog.go#L42-L51

**Comment by progrium** [comment]
That should it shouldn't error like that, so you found a bug. Thanks for reporting. :)

**Comment by nagliyvred** [comment]
So, does it mean my url should be `syslog://logs-01.loggly.com:514?structuredData=<token>@41058` now? 
That still gives me the same error :( 
Anything I can do to make it work in the meantime?

**Comment by progrium** [comment]
structuredData is now structured_data but other than that I'll look into it
after dinner and see if I can get a fix for you.

On Monday, April 6, 2015, Evgeny Dudin <notifications@github.com> wrote:

> So, does it mean my url should be syslog://
> logs-01.loggly.com:514?structuredData=<token>@41058 now?
> That still gives me the same error :(
> Anything I can do to make it work in the meantime?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/logspout/issues/75#issuecomment-90304735>.
>


-- 
Jeff Lindsay
http://progrium.com

**Comment by nagliyvred** [comment]
Thanks Jeff, appreciate it!
